declare module 'lucide-react' {
  import { FC, SVGProps, ReactElement } from 'react'
  type Icon = FC<SVGProps<SVGSVGElement> & { size?: number | string }>

  export const Send: Icon
  export const Trash2: Icon
  export const Leaf: Icon
  export const Loader2: Icon
  export const ChevronDown: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const RefreshCw: Icon
  export const AlertCircle: Icon
  export const User: Icon
  export const Zap: Icon
  export const Crown: Icon
  export const Star: Icon
  export const Lock: Icon
  export const X: Icon
  export const Check: Icon
  export const Sparkles: Icon
  export const Utensils: Icon
  export const ShoppingCart: Icon
  export const ChefHat: Icon
  export const LogOut: Icon
  export const Stethoscope: Icon
  export const ArrowDown: Icon
  export const UserCircle: Icon
  export const Scale: Icon
  export const Droplets: Icon
  export const Flame: Icon
  export const Plus: Icon
  export const Minus: Icon
  export const Heart: Icon
  export const MessageCircle: Icon
  export const ThumbsUp: Icon
  export const ThumbsDown: Icon
  export const BarChart3: Icon
  export const Edit3: Icon
  export const Eye: Icon
  export const Clock: Icon
  export const Calendar: Icon
  export const TrendingUp: Icon
  export const TrendingDown: Icon
  export const Target: Icon
  export const Award: Icon
  export const Bell: Icon
  export const Search: Icon
  export const Settings: Icon
  export const HelpCircle: Icon
  export const ChevronUp: Icon
  export const MoreHorizontal: Icon
  export const SendHorizontal: Icon
  export const Copy: Icon
  export const ExternalLink: Icon
  export const Phone: Icon
  export const Mail: Icon
  export const FileText: Icon
  export const Download: Icon
  export const Upload: Icon
  export const Image: Icon
  export const Camera: Icon
  export const Video: Icon
  export const Mic: Icon
  export const Headphones: Icon
  export const Music: Icon
  export const BookOpen: Icon
  export const Globe: Icon
  export const MapPin: Icon
  export const CalendarDays: Icon
  export const Info: Icon
  export const AlertTriangle: Icon
  export const CheckCircle: Icon
  export const XCircle: Icon
  export const Filter: Icon
  export const SortAsc: Icon
  export const SortDesc: Icon
  export const Grid: Icon
  export const List: Icon
  export const PieChart: Icon
  export const LineChart: Icon
  export const BarChart: Icon
  export const Activity: Icon
  export const ZapOff: Icon
  export const Power: Icon
  export const Menu: Icon
  export const MoreVertical: Icon
  export const ArrowRight: Icon
  export const ArrowLeft: Icon
  export const ArrowUp: Icon
  export const ArrowDownCircle: Icon
  export const CheckSquare: Icon
  export const Square: Icon
  export const Circle: Icon
  export const Layers: Icon
  export const Package: Icon
  export const Box: Icon
  export const Truck: Icon
  export const Building: Icon
  export const Home: Icon
  export const Users: Icon
  export const DollarSign: Icon
  export const CreditCard: Icon
  export const Percent: Icon
  export const Hash: Icon
  export const AtSign: Icon
  export const Tag: Icon
  export const Bookmark: Icon
  export const BookmarkFilled: Icon
  export const Save: Icon
  export const Share: Icon
  export const Share2: Icon
  export const Printer: Icon
  export const Bold: Icon
  export const Italic: Icon
  export const Underline: Icon
  export const Link: Icon
  export const Unlink: Icon
  export const Maximize2: Icon
  export const Minimize2: Icon
  export const Expand: Icon
  export const Shrink: Icon
  export const RotateCcw: Icon
  export const RotateCw: Icon
  export const FlipHorizontal: Icon
  export const FlipVertical: Icon
  export const GripVertical: Icon
  export const ZoomIn: Icon
  export const ZoomOut: Icon
  export const EyeOff: Icon
  export const ToggleLeft: Icon
  export const ToggleRight: Icon
  export const Trash: Icon
  export const Edit: Icon
  export const Edit2: Icon
  export const Pencil: Icon
  export const File: Icon
  export const Folder: Icon
  export const FolderOpen: Icon
  export const FolderPlus: Icon
  export const FolderMinus: Icon
  export const Code: Icon
  export const Code2: Icon
  export const Terminal: Icon
  export const Cpu: Icon
  export const HardDrive: Icon
  export const Database: Icon
  export const Server: Icon
  export const Cloud: Icon
  export const CloudOff: Icon
  export const UploadCloud: Icon
  export const DownloadCloud: Icon
  export const Shield: Icon
  export const ShieldCheck: Icon
  export const ShieldAlert: Icon
  export const ShieldOff: Icon
  export const LockKeyhole: Icon
  export const Unlock: Icon
  export const Key: Icon
  export const KeyRound: Icon
  export const TwoFactorAuthentication: Icon
  export const Fingerprint: Icon
  export const Scan: Icon
  export const ScanLine: Icon
  export const QrCode: Icon
  export const Barcode: Icon
  export const Wifi: Icon
  export const WifiOff: Icon
  export const Bluetooth: Icon
  export const BluetoothConnected: Icon
  export const Signal: Icon
  export const SignalZero: Icon
  export const SignalLow: Icon
  export const SignalMedium: Icon
  export const SignalHigh: Icon
  export const Battery: Icon
  export const BatteryCharging: Icon
  export const BatteryFull: Icon
  export const BatteryLow: Icon
  export const BatteryMedium: Icon
  export const Plug: Icon
  export const PlugZap: Icon
  export const Monitor: Icon
  export const Tv: Icon
  export const Smartphone: Icon
  export const Tablet: Icon
  export const Watch: Icon
  export const Laptop: Icon
  export const Speaker: Icon
  export const Volume: Icon
  export const Volume1: Icon
  export const Volume2: Icon
  export const VolumeX: Icon
  export const Mic2: Icon
  export const MicOff: Icon
  export const MessageSquare: Icon
  export const MessageSquareDashed: Icon
  export const MessageSquarePlus: Icon
  export const Inbox: Icon
  export const SendToBack: Icon
  export const MailOpen: Icon
  export const MailPlus: Icon
  export const MailSearch: Icon
  export const MailWarning: Icon
  export const MailX: Icon
  export const InboxArrowDown: Icon
  export const InboxArrowUp: Icon
  export const GitBranch: Icon
  export const GitCommit: Icon
  export const GitMerge: Icon
  export const GitPullRequest: Icon
  export const GitCompare: Icon
  export const CircleDot: Icon
  export const CircleDashed: Icon
  export const CircleSmall: Icon
  export const Octagon: Icon
  export const Pentagon: Icon
  export const Hexagon: Icon
  export const Triangle: Icon
  export const Rhombus: Icon
  export const Diamond: Icon
  export const LayoutDashboard: Icon
  export const LayoutTemplate: Icon
  export const Layout: Icon
  export const PanelLeft: Icon
  export const PanelRight: Icon
  export const PanelTop: Icon
  export const PanelBottom: Icon
  export const PanelLeftClose: Icon
  export const PanelRightClose: Icon
  export const Wand2: Icon
  export const Sparkles: Icon
  export const Feather: Icon
  export const Dot: Icon
  export const Crown: Icon
  export const Sword: Icon
  export const Shield: Icon
  export const Skull: Icon
  export const Ghost: Icon
  export const Pumpkin: Icon
  export const Fish: Icon
  export const Bird: Icon
  export const Cat: Icon
  export const Dog: Icon
  export const Rabbit: Icon
  export const Turtle: Icon
  export const Bug: Icon
  export const Worm: Icon
  export const Flower: Icon
  export const Flower2: Icon
  export const TreePine: Icon
  export const TreeDeciduous: Icon
  export const Mountain: Icon
  export const Waves: Icon
  export const CloudRain: Icon
  export const CloudSnow: Icon
  export const CloudLightning: Icon
  export const CloudSun: Icon
  export const CloudMoon: Icon
  export const CloudFog: Icon
  export const Sunrise: Icon
  export const Sunset: Icon
  export const Moon: Icon
  export const Sun: Icon
  export const Thermometer: Icon
  export const ThermometerSun: Icon
  export const ThermometerSnowflake: Icon
  export const Umbrella: Icon
  export const Wind: Icon
  export const Droplet: Icon
  export const Droplets: Icon
  export const Compass: Icon
  export const Navigation: Icon
  export const Map: Icon
  export const MapPin: Icon
  export const Orbit: Icon
  export const Cookie: Icon
  export const Candy: Icon
  export const Apple: Icon
  export const Cherry: Icon
  export const Grape: Icon
  export const Banana: Icon
  export const Carrot: Icon
  export const Egg: Icon
  export const FishSymbol: Icon
  export const Ham: Icon
  export const IceCream: Icon
  export const Milk: Icon
  export const Pepper: Icon
  export const Pizza: Icon
  export const Rice: Icon
  export const Salad: Icon
  export const Sandwich: Icon
  export const Soup: Icon
  export const Utensils: Icon
  export const Wine: Icon
  export const Beer: Icon
  export const Coffee: Icon
  export const CupSoda: Icon
  export const GlassWater: Icon
  export const GlassWine: Icon
  export const CandyCane: Icon
  export const Cookie: Icon
  export const Apple: Icon
  export const Cherry: Icon
}
